# Generated by Django 4.1.4 on 2023-01-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slammers_api', '0003_remove_customer_name_customer_email_and_more'),
        ('slammers_api', '0004_goods_rename_product_boards_and_more'),
    ]

    operations = [
    ]
